config/routes.rb
Rails.application.routes.draw do
  root "books#search"

  resources :books do
    collection do
      get 'search'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def search
    if params[:keyword]
      books = RakutenWebService::Books::Book.search(title: params[:keyword])

      @books_hash = []
      books.each do |book|
        @books_hash.push(book)
      end
      @books = Kaminari.paginate_array(@books_hash).page(params[:page]).per(15)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book-list.html.haml
- @books.each do |book|
  .search-result__container__lists
    - if book.item_url
      .book_image
        = link_to (image_tag(book.medium_image_url, style: "width: auto; height: auto; display: inline-block;")), book.item_url
      .book_title
        = book.title
      .book_author
        = book.author
      .book_caption
        出版社名：
        = book.publisher_name
      .book_price
        ¥
        = book.item_price.to_s(:delimited)

app/views/books/_book.html.haml
- @books.each do |book|
  .search-result__container__lists
    - if book.item_url
      .book_image
        = link_to (image_tag(book.medium_image_url, style: "width: auto; height: auto; display: inline-block;")), book.item_url
      .book_title
        = book.title
      .book_author
        = book.author
      .book_caption
        出版社名：
        = book.publisher_name
      .book_price
        ¥
        = book.item_price.to_s(:delimited)

app/views/books/search.html.haml
%header
  .nav
    = link_to "Book Search WEB Site", "/", class: "nav-title"
    
  .fv-view
    .fv-view__textbox
      %p 人生を彩る。人生を変える。
      %p そんな一冊を、探してみよう。



.search_box
  = form_with url: search_books_path, method: :get, class: "form-box",local: true do |f|
    .search_box__form
      = f.text_field :keyword, class: "input-form", placeholder: "本のタイトルを入力してください"
    .search_box__btn
      = f.submit '本のタイトルで検索', class: "submit-btn"

.search-result
- if @books.present?
  .search-result__message
    ▽   気になった本の画像をクリックすると、楽天Booksの詳細情報画面に飛びます  ▽
  .search-result__container
    = render 'books/book-list'

- if @books.present?
  = paginate @books, class: "pagination"


%footer
  -# Rakuten Web Services Attribution Snippet FROM HERE
  -# <a href="https://webservice.rakuten.co.jp/" target="_blank">Supported by Rakuten Developers</a>
  = link_to "Supported by Rakuten Developers", "https://webservice.rakuten.co.jp/",target: "_blank", class: "footer-text"
  -# Rakuten Web Services Attribution Snippet TO HERE

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ApiApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield